Algoritmo "SE"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/04/2022
Var
// Seção de Declarações das variáveis 
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   SE i>0 ENTAO
      ESCREVAL("I MAIOR QUE ZERO")
   SENAO
      ESCREVAL("I MENOR QUE ZERO")
   FIMSE
Fimalgoritmo